logo: "/images/logo.png"
title: "MPDieckmann"
sidebar: "sidebar-widgets.html"
footer: "footer-widgets.html"
headermenu: [
  { url: "/", title: "Home" },
  { url: "/Snippets/", title: "Snippets" },
  { url: "/wp-plugins/", title: "WP-Plugins" },
  { url: "/wp-themes/", title: "WP-Themes" }
]
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      appbackground: "#eee"
      cardbackground: "#fff"
      themecolor: "#080"
      themedforecolor: "#fff"
      layout: "default"
      author: "<a href=\"https://github.com/MPDieckmann\">MPDieckmann</a>"
  -
    scope:
      path: ""
      type: "posts"
    values:
      showmeta: "true"
      appbackground: "#eee"
      cardbackground: "#fff"
      themecolor: "#080"
      themedforecolor: "#fff"
      layout: "default"
      author: "<a href=\"https://github.com/MPDieckmann\">MPDieckmann</a>"
